// The discoverability metadata has to still be there, and still be true.
//
// Every check below is for something that fails silently. A dropped `og:image`
// turns every share back into a bare link and the page looks identical. A
// relative `og:image` is ignored by most scrapers rather than rejected. A
// JSON-LD graph with a typo is skipped by the consumer, not reported. A link in
// `llms.txt` that points at a page nobody built any more is a 404 handed
// specifically to the crawlers this file exists to serve.
//
// It reads the *built* output for the reason verify-lang.mjs does: a check
// against the source can pass while the shipped page does something else. In
// this repo that has happened — a feature once shipped to production inert
// because Astro printed the wrapper around a JSX expression into the document.
//
// When the metadata changes, change the expectations here with it.

import { readdirSync, readFileSync, existsSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
const ORIGIN = "https://spacetrace.teknobakkall.com";

/** Must agree with OG_IMAGE in src/data/seo.ts. */
const OG = { file: "og.png", width: 1200, height: 630 };

const problems = [];
const note = (m) => problems.push(m);

if (!existsSync(dist)) {
  console.error("verify-seo failed:\n  no dist/. Run `yarn build` first.");
  process.exit(1);
}

/** Every built page, as paths relative to dist/. */
function htmlFiles(dir = dist) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...htmlFiles(full));
    else if (entry.name.endsWith(".html")) out.push(full);
  }
  return out;
}

const pages = htmlFiles();
if (pages.length < 30) {
  note(`only ${pages.length} built pages found; the site has 36. Stale dist?`);
}

const attr = (html, selector, name) => {
  // Deliberately crude: a real parser is a dependency, and the markup this
  // reads is generated by one layout file. A match failure here means the tag
  // is missing or was rewritten, both of which are worth a look.
  const tag = html.match(new RegExp(`<meta[^>]*${selector}[^>]*>`, "i"));
  if (!tag) return null;
  const value = tag[0].match(new RegExp(`${name}="([^"]*)"`, "i"));
  return value ? value[1] : null;
};

let graphs = 0;
let indexable = 0;

for (const file of pages) {
  const path = relative(dist, file);
  const html = readFileSync(file, "utf8");
  const is404 = path === "404.html";

  const robots = attr(html, 'name="robots"', "content");
  if (!robots) {
    note(`${path}: no robots meta`);
  } else if (is404) {
    if (!robots.includes("noindex")) {
      note(`${path}: the error page must be noindex, got "${robots}"`);
    }
  } else {
    indexable += 1;
    if (robots.includes("noindex")) {
      note(`${path}: noindex on a real page`);
    }
    if (!robots.includes("max-image-preview:large")) {
      note(`${path}: robots meta is missing max-image-preview:large`);
    }
  }

  const canonical = html.match(/<link[^>]*rel="canonical"[^>]*href="([^"]*)"/i);
  if (!canonical) note(`${path}: no canonical`);
  else if (!canonical[1].startsWith(ORIGIN)) {
    note(`${path}: canonical is not absolute on this origin: ${canonical[1]}`);
  }

  const image = attr(html, 'property="og:image"', "content");
  if (!image) note(`${path}: no og:image`);
  else if (!image.startsWith("https://")) {
    // The failure this catches is a scraper silently showing no card at all.
    note(`${path}: og:image must be an absolute URL, got "${image}"`);
  }

  if (attr(html, 'name="twitter:card"', "content") !== "summary_large_image") {
    note(`${path}: twitter:card is not summary_large_image`);
  }

  if (!attr(html, 'property="og:site_name"', "content")) {
    note(`${path}: no og:site_name`);
  }

  const ogLocale = attr(html, 'property="og:locale"', "content");
  if (!ogLocale) note(`${path}: no og:locale`);
  else if (!/^[a-z]{2}_[A-Z]{2}$/.test(ogLocale)) {
    // A bare `en` parses as nothing to the scrapers that read this field.
    note(`${path}: og:locale must be language_TERRITORY, got "${ogLocale}"`);
  }

  const ld = html.match(
    /<script[^>]*type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/i,
  );
  if (is404) {
    if (ld) note(`${path}: the error page should carry no JSON-LD`);
    continue;
  }
  if (!ld) {
    note(`${path}: no JSON-LD`);
    continue;
  }

  let parsed;
  try {
    parsed = JSON.parse(ld[1]);
  } catch (err) {
    // The shape this catches: the graph arriving as an escaped string, which
    // is what happens when a template child is used instead of set:html.
    note(`${path}: JSON-LD does not parse — ${err.message}`);
    continue;
  }
  graphs += 1;

  const nodes = parsed["@graph"];
  if (!Array.isArray(nodes) || nodes.length === 0) {
    note(`${path}: JSON-LD has no @graph`);
    continue;
  }
  if (parsed["@context"] !== "https://schema.org") {
    note(`${path}: JSON-LD @context is "${parsed["@context"]}"`);
  }
  const types = nodes.map((n) => n["@type"]);
  for (const required of ["WebSite", "WebPage", "Organization"]) {
    if (!types.includes(required)) {
      note(`${path}: JSON-LD is missing a ${required} node`);
    }
  }
  for (const node of nodes) {
    if (!node["@type"]) note(`${path}: a JSON-LD node has no @type`);
    for (const [key, value] of Object.entries(node)) {
      if (typeof value === "string" && value.includes("undefined")) {
        note(`${path}: JSON-LD ${node["@type"]}.${key} contains "undefined"`);
      }
    }
  }
  // Only the three component pages may price themselves, and only the free one
  // does. See the rules in src/data/structuredData.ts.
  const app = nodes.find((n) => n["@type"] === "SoftwareApplication");
  if (app && app.offers && !app.isAccessibleForFree) {
    note(`${path}: JSON-LD declares an offer without isAccessibleForFree`);
  }
}

// ----------------------------------------------------------- public files

const robotsFile = join(dist, "robots.txt");
if (!existsSync(robotsFile)) {
  note("robots.txt is not in dist/");
} else {
  const text = readFileSync(robotsFile, "utf8");
  const sitemap = text.match(/^Sitemap:\s*(\S+)$/im);
  if (!sitemap) {
    note("robots.txt has no Sitemap line, which is the only reason it exists");
  } else {
    // A Sitemap line pointing at a file that is not built is the exact failure
    // that leaves a crawler discovering 36 pages by hand.
    const name = sitemap[1].replace(`${ORIGIN}/`, "");
    if (!existsSync(join(dist, name))) {
      note(`robots.txt points at ${name}, which dist/ does not contain`);
    }
  }
  for (const agent of ["GPTBot", "ClaudeBot", "PerplexityBot"]) {
    if (!text.includes(agent)) note(`robots.txt no longer names ${agent}`);
  }
}

const llms = join(dist, "llms.txt");
if (!existsSync(llms)) {
  note("llms.txt is not in dist/");
} else {
  const text = readFileSync(llms, "utf8");
  const links = [...text.matchAll(/\]\((https:\/\/[^)]+)\)/g)].map((m) => m[1]);
  const ownPages = links.filter((u) => u.startsWith(ORIGIN));
  if (ownPages.length < 7) {
    note(`llms.txt links to only ${ownPages.length} of its own pages`);
  }
  for (const url of ownPages) {
    const path = url.slice(ORIGIN.length).replace(/^\/+/, "");
    const target = path === "" ? "index.html" : join(path, "index.html");
    if (!existsSync(join(dist, target))) {
      note(`llms.txt links to ${url}, which dist/ does not contain`);
    }
  }
}

const og = join(dist, OG.file);
if (!existsSync(og)) {
  note(`${OG.file} is not in dist/`);
} else {
  // PNG dimensions come out of the IHDR chunk: 8 bytes of signature, then a
  // 4-byte length and the "IHDR" tag, then width and height as big-endian
  // 32-bit integers. Cheaper than a dependency and it cannot go out of date.
  const head = readFileSync(og).subarray(0, 24);
  const width = head.readUInt32BE(16);
  const height = head.readUInt32BE(20);
  if (width !== OG.width || height !== OG.height) {
    note(
      `${OG.file} is ${width}×${height}; src/data/seo.ts declares ` +
        `${OG.width}×${OG.height}, and the declared size is what scrapers lay out`,
    );
  }
  if (statSync(og).size < 8000) {
    note(`${OG.file} is suspiciously small; it may have rendered blank`);
  }
}

if (problems.length > 0) {
  console.error("verify-seo failed:\n  " + problems.join("\n  "));
  process.exit(1);
}

console.log(
  `verify-seo: ${pages.length} pages checked, ${indexable} indexable, ` +
    `${graphs} JSON-LD graphs parsed; robots.txt, llms.txt and ${OG.file} present and consistent.`,
);
