/**
 * The handful of SEO values that are the same on every page, in one place so
 * that changing one is one edit rather than a sweep through the layout.
 */

/** Used for `og:site_name` and as the site's name in JSON-LD. */
export const SITE_NAME = "spacetrace";

/**
 * The share card.
 *
 * One image for every page and every language, deliberately. The page-specific
 * part of a share is already carried by `og:title` and `og:description`, which
 * are translated; the image does the brand's job. Seven per-page cards would
 * each contain a page name baked into pixels, and `verify-seo.mjs` cannot read
 * text out of a PNG — so a renamed page would leave a wrong image behind with
 * nothing to catch it.
 *
 * Regenerated by hand from `scripts/og-card.html`; that file's header has the
 * steps, and there is deliberately no command for it. The dimensions below
 * must match the card's own CSS, and `yarn verify:seo` reads the real ones out
 * of the PNG to check. They are declared to the scrapers because a card whose
 * size is not known up front is often rendered small.
 */
export const OG_IMAGE = {
  file: "og.png",
  width: 1200,
  height: 630,
  /** Describes the card itself, not the page; it is the same on all of them. */
  alt: "spacetrace — a treemap of a disk, with the folder that grew highlighted",
} as const;

/**
 * Search-console ownership tokens.
 *
 * These are not secrets — the whole point is that they are publicly readable
 * on the page — but they are account-specific and have to be pasted in from
 * Google Search Console and Bing Webmaster Tools. An empty string renders no
 * tag at all, which is why the default is empty rather than a placeholder that
 * would ship a broken verification.
 *
 * Bing can import a verified property straight from Search Console, so filling
 * in `google` alone is usually enough; `bing` is here for the case where it is
 * verified directly.
 */
export const VERIFICATION = {
  google: "",
  bing: "",
} as const;
